Repository go-gitea/theme, pull requests merged in 2018-05, with the labels that each got.

#53 Always ensure there's a title
  layouts/partials/header.html
Labels: lgtm/done

#54 New design
  layouts/_default/single.html
  layouts/doc/single.html
  layouts/home/index.html
  layouts/home/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/partials/pages.html
  layouts/partials/toplinks.html
  layouts/post/list.html
  layouts/post/single.html
  package.json
  src/colors.scss
  src/landingpage.scss
  src/main.scss
  static/images/screenshot.jpg
Labels: kind/enhancement, lgtm/done

#56 Fix 404 image
  layouts/home/index.html
Labels: kind/bug, lgtm/done

#58 check in package-lock
  package-lock.json
Labels: lgtm/done

#57 fix padding on mobile
  layouts/_default/single.html
  layouts/doc/single.html
  layouts/page/single.html
  src/main.scss
Labels: lgtm/done

#59 Add screenshot with higher resolution and PNG format
  layouts/home/index.html
  static/images/screenshot.jpg
  static/images/screenshot.png
Labels: lgtm/done
